package sys.model;
// Generated 15/06/2024 11:11:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE")

public class Cliente implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CODCLIENTE")
    private int codcliente;
    @Column(name = "NOMBRES")
    private String nombres;
    @Column(name = "IDENTIFICACION")
    private String identificacion;
    @Column(name = "APELLIDOS")
    private String apellidos;
    @Column(name = "CELULAR")
    private String celular;
    @Column(name = "DIRECCION")
    private String dirrecion;
    @Column(name = "EMAIL")
    private String email;
    private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

    public Cliente(int codcliente, String nombres, String apellidos, String celular, String dirrecion, String identificacion, String email) {
        this.codcliente = codcliente;
        this.nombres = nombres;
        this.identificacion = identificacion;
        this.apellidos = apellidos;
        this.celular = celular;
        this.dirrecion = dirrecion;
        this.email = email;

    }

    public Cliente(int codcliente, String nombres, String apellidos, String celular, String dirrecion, String identificacion, String email, Set<Factura> facturas) {
        this.codcliente = codcliente;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.celular = celular;
        this.dirrecion = dirrecion;
        this.facturas = facturas;
    }

    public int getCodcliente() {
        return this.codcliente;
    }

    public void setCodcliente(int codcliente) {
        this.codcliente = codcliente;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getDirrecion() {
        return this.dirrecion;
    }

    public void setDirrecion(String dirrecion) {
        this.dirrecion = dirrecion;
    }

    public Set<Factura> getFacturas() {
        return this.facturas;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

}
