package sys.model;
// Generated 15/06/2024 11:11:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codcliente;
     private String nombres;
     private String apellidos;
     private String celular;
     private String dirrecion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(int codcliente, String nombres, String apellidos, String celular, String dirrecion) {
        this.codcliente = codcliente;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.celular = celular;
        this.dirrecion = dirrecion;
    }
    public Cliente(int codcliente, String nombres, String apellidos, String celular, String dirrecion, Set<Factura> facturas) {
       this.codcliente = codcliente;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.celular = celular;
       this.dirrecion = dirrecion;
       this.facturas = facturas;
    }
   
    public int getCodcliente() {
        return this.codcliente;
    }
    
    public void setCodcliente(int codcliente) {
        this.codcliente = codcliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDirrecion() {
        return this.dirrecion;
    }
    
    public void setDirrecion(String dirrecion) {
        this.dirrecion = dirrecion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


